name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v2

      - name: Run tests
        run: swift test
